server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8
  context-path: /api

mybatis:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: com.dalian.sea.model


spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    http:
        multipart:
          max-file-size: 3Mb
          max-request-size: 3Mb
    datasource:
        name: test
        url: jdbc:mysql://rm-2ze9gz5ek00e864660o.mysql.rds.aliyuncs.com:3306/dalian?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: Lduwa808
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # wall用于防火墙
        filters: stat
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 3

#druid console
druid:
    loginUsername: admin
    loginPassword: 123456
    resetEnable: false

aliyun:
    oss:
        endpoint: https://oss-cn-shanghai.aliyuncs.com
        accessKeyId: LTAIHmlWzXmr6sDn
        accessKeySecret: 5Noh2L7rdNAD4OK5I0snQeNUbQyDuM
        bucketName: yzs2
        firstKey: my-first-key
        filedir: img/
        filedirV: video/
