server:
  port: 9090
  tomcat:
      uri-encoding: UTF-8
  context-path: /back

mybatis:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: com.dalian.sea.model



myLayout:
    #需要装饰的访问路径
    contentPath: .htm
    #装饰器页面路径
    decoratorPath: layout/home
    #不需要装饰的访问路径,多个之间用英文逗号分隔
    excludedPaths: 403.htm,404.htm,Modal.htm,login.htm

spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    http:
        multipart:
          max-file-size: 600Mb
          max-request-size: 600Mb
    datasource:
        name: test
        url: jdbc:mysql://rm-2ze1bss140bhueva3.mysql.rds.aliyuncs.com:3306/dalian?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: Lduwa808
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # wall用于防火墙
        filters: stat
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 3
    resources:
        static-locations: classpath:/static/
    freemarker:
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        check-template-location: true
        template-loader-path: classpath:/templates/
        static-path-pattern: /static/**
        cache: false
        settings:
            number_format: '0.##'
            template_update_delay: 0
    redis:
        database: 2
        secondary-database: 11
        host: 59.110.169.186
        port: 6680
        password: Lvdu&%808test.DB
        timeout: 2000
        max-active: 8
        max-total: 50
        max-wait-millis: 15000
        test-on-borrow: true
        max-idle: 10
        max-wait: -1
        min-idle: 0
        session-expire: 1800

#druid console
druid:
    loginUsername: admin
    loginPassword: 123456
    resetEnable: false

aliyun:
    oss:
        endpoint: https://oss-cn-beijing.aliyuncs.com
        accessKeyId: LTAIjIZDrb2jPZEG
        accessKeySecret: IMvWwEF9a1v2iqOuqtBJMkOCNi4APf
        bucketName: dalianxiaoqin
        filedir: img/
        filedirV: video/
crm-url: http://47.92.118.231/